theme: minima

minima: 
  skin: solarized

header_pages:
  - oraa2024.md
  - alra.md
  - rsss.md
  
plugins:
  - jekyll-feed

title: Açores.net
description: Repositório de dados sobre os Açores
collections:
  alra_updates:
      output: true 
      permalink: /alra_updates/:path/
  joraa_updates:
      output: true 
      permalink: /joraa_updates/:path/
  base_updates:
      output: true 
      permalink: /base_updates/:path/
  portal_updates:
