name: Daily `bot` run 
on:
  schedule:
    - cron: '00 00 * * *'  # Runs daily at midnight UTC
jobs:
  daily-bot-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r bot/requirements.txt
      - name: Run bot
        run: python -m bot
      - name: Configure git
        run: |
          git config --global user.name "fmesqg-auto" 
          git config --global user.email ""
          
      - name: Commit and push if there are changes
      # count new files or diff to existing
        run: |
          if [ $(git ls-files -o --exclude-standard | wc -l) -gt 0 ] || [[ $(git diff --name-only | wc -l) -gt 0 ]]
          then
            git add .
            git commit -m "Daily bot update"
            git push origin main
            echo "Wrote update."
          else
            echo "Nothing to write."
          fi